server:
  servlet:
    contextPath: /news-service
  port: 8087

integration:
  police-service:
    url: http://police-service:8089/police-service/v1/police/news
  sport-service:
    url: http://sport-service:8081/sport-service/external/v1/sport-news
